spring.application.name=webAppStudents
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trabajo_final_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará las tablas si no existen y las actualizará si hay cambios en tus entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
